abstract class BackgroundImageState {}

class BackgroundImageIinitialState extends BackgroundImageState {}
class GetBackgroundImageLoadingState extends BackgroundImageState{}
class GetBackgroundImageSuccessState extends BackgroundImageState{}
class GetBackgroundImageSuccessWithoutData extends BackgroundImageState{}
class GetBackgroundImageErrorState extends BackgroundImageState{}
